'use client';
import { useState } from 'react';
import { Activity, ArrowRight, CheckCircle2, ChevronDown, CircleDot, Download, FileImage, Gauge, Layers3, Moon, Play, RotateCcw, Satellite, Settings2, ShieldCheck, UploadCloud, X, Crosshair } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { NativeSelect } from '@/components/ui/native-select';
import { Progress, ProgressLabel, ProgressValue } from '@/components/ui/progress';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from '@/components/ui/dropdown-menu';
import { Dialog, DialogContent, DialogDescription, DialogTitle } from '@/components/ui/dialog';
import { LunarViewer, type ViewMode } from '@/components/lunar-viewer';
import { DEMO_IMAGE, PIPELINE } from '@/lib/lunar-data';
import { useLunarWorkspace } from '@/hooks/use-lunar-workspace';
export default function Home(){
  const w=useLunarWorkspace();
  const [coverageSize,setCoverageSize]=useState({width:1300,height:1300});
  const {source,reference,stage,completed,simulated,uploaded,metrics,points,selected}=w;
  return <main className="min-h-screen bg-background text-foreground">
    <header className="topbar"><div className="brand"><div className="brand-mark"><Moon/></div><div><strong>LUNARGRID</strong><span>CHANDRA-ALIGN</span></div></div><div className="mission"><span className="live-dot"/> SIH 26166 · MISSION WORKSPACE</div><div className="top-actions"><span className="system-ok"><ShieldCheck/> Prototype workspace</span><Button variant="outline" size="sm" onClick={()=>{w.setDraftEndpoint(w.endpoint);w.setSettingsOpen(true);}}><Settings2/> Settings</Button></div></header>
    <div className="workflow-strip">{['LOAD LUNAR DATA','READ METADATA','RUN REGISTRATION','INSPECT MATCHES','CHECK QUALITY','EXPORT'].map((s,i)=><span key={s} className={i===2?'current':''}>{i>0&&<ArrowRight/>}{String(i+1).padStart(2,'0')} {s}</span>)}</div>
    <section className="workspace-shell">
      <aside className="side-panel"><div className="eyebrow">INPUT PAIR</div><h1>Register lunar imagery</h1><p className="subcopy">Align multi-sensor tiles across scale, illumination and viewing geometry.</p>
        {(['source','reference'] as const).map(target=>{const data=target==='source'?source:reference;return <label className="upload-card" key={target}><input aria-label={`Load ${target} image`} disabled={stage==='running'} type="file" accept="image/*,.tif,.tiff,.img" onChange={e=>{w.loadImage(e.target.files?.[0],target);e.target.value='';}}/>{target==='source'?<UploadCloud/>:<Layers3/>}<span><b>{target==='source'?'Source image':'Reference image'}</b><small title={data.name}>{data.name}</small><em>{data.file?'LOCAL FILE':'SAMPLE DATASET'}</em></span><CheckCircle2 className="file-ok"/></label>;})}
        <label className="upload-card compact"><input aria-label={`Load ${w.labelTarget} PDS4 label`} disabled={stage==='running'} type="file" accept=".xml" onChange={e=>{void w.loadMetadata(e.target.files?.[0]);e.target.value='';}}/><FileImage/><span><b>PDS4 label</b><small>{(w.labelTarget==='source'?source:reference).label||'Load XML to detect metadata'}</small></span></label>
        <div className="label-target"><span>Label applies to</span>{(['source','reference'] as const).map(target=><button key={target} disabled={stage==='running'} aria-pressed={w.labelTarget===target} onClick={()=>w.setLabelTarget(target)}>{target==='source'?'Source':'Reference'}</button>)}</div>
        <div className="section-caption">SOURCE METADATA {!source.file&&<span>EXAMPLE</span>}</div><div className="metadata-grid">{[['SENSOR',source.metadata.sensor],['GSD',source.metadata.gsd],['SUN AZ.',source.metadata.sun],['SCALE GAP',w.scaleGap]].map(([label,value])=><div key={label}><span>{label}</span><b>{value}</b></div>)}</div>
        <div className="reference-meta"><span>REFERENCE</span><b>{reference.metadata.sensor}</b><small>GSD {reference.metadata.gsd} · Sun {reference.metadata.sun}</small></div>
        <div className="mode-box"><div><span>REGISTRATION METHOD</span><b>{uploaded?'Configured processing service':'Auto → LightGlue'}</b></div><p>{uploaded?'The backend reports its actual matching and alignment method.':'Automatic matching · TPS alignment'}{!uploaded&&<em>Simulated method selection</em>}</p></div>
        {w.error&&<div className="error-note" role="alert">{w.error}</div>}<Button className="run-button" size="lg" onClick={()=>void w.run()} disabled={stage==='running'}>{stage==='running'?<Activity/>:<Play/>}{stage==='running'?'Registering…':'Run Registration'}</Button><p className="run-note">{uploaded?'Uploaded files are sent only when you run.':'Replays the simulated registration pipeline.'}</p><Button variant="ghost" className="reset-button" onClick={w.resetDemo}><RotateCcw/>{stage==='running'?'Cancel & load sample pair':'Load sample pair'}</Button>
      </aside>
      <section className="main-stage"><div className="stage-heading"><div><div className="eyebrow">REGISTRATION VIEW</div><h2>{uploaded?'Custom lunar image pair':'Lunar surface test pair'}</h2></div><div className={`result-chip ${stage}`}><CircleDot/>{stage==='running'?'Processing':completed?(simulated?'Simulation complete':'Registration complete'):'Ready'}</div></div>
        <Tabs className="view-tabs" value={w.mode} onValueChange={v=>w.setMode(v as ViewMode)}><TabsList aria-label="Image viewing modes"><TabsTrigger value="comparison">Comparison</TabsTrigger><TabsTrigger value="tie-points">Tie Points</TabsTrigger><TabsTrigger value="overlay" disabled={!completed}>Overlay</TabsTrigger><TabsTrigger value="registered" disabled={!completed}>Registered</TabsTrigger></TabsList><TabsContent value={w.mode} aria-label={`${w.mode} image view`}><LunarViewer mode={w.mode} source={w.sourcePreview} reference={w.referencePreview} registered={w.result?.aligned_preview||(!uploaded?DEMO_IMAGE:null)} simulated={!uploaded} points={w.showRejected?points:points.filter(p=>p.status==='accepted')} selected={selected} onSelect={w.setSelected}/></TabsContent></Tabs>
        {!uploaded&&<p className="imagery-credit">Imagery: Tycho crater · LROC WAC · NASA/GSFC/Arizona State University. <a href="https://science.nasa.gov/image-detail/amf-cc06843a-5b68-4cb4-9119-c62e383b54fa/" target="_blank" rel="noreferrer">Source ↗</a><span>Example dataset names and metadata; one photograph used for the simulated pair.</span></p>}
        {w.mode==='tie-points'&&<div className="tie-inspector"><div className="inspector-head"><b><Crosshair/> Tie-point inspection</b><label><Checkbox checked={w.showRejected} onCheckedChange={w.setShowRejected}/> Show rejected</label></div>{points.length?<><div className="match-selection"><label htmlFor="match-select">Match ID</label><NativeSelect id="match-select" value={selected?.id||''} onChange={e=>w.setSelected(points.find(p=>p.id===e.target.value)||null)}><option value="">Select a point or match…</option>{points.map(p=><option key={p.id} value={p.id}>{p.id} · {p.status}</option>)}</NativeSelect><span>{points.length} correspondences</span></div>{selected?<dl className="match-details"><div><dt>Source X / Y</dt><dd>{selected.source_x.toFixed(2)} / {selected.source_y.toFixed(2)}</dd></div><div><dt>Reference X / Y</dt><dd>{selected.reference_x.toFixed(2)} / {selected.reference_y.toFixed(2)}</dd></div><div><dt>Confidence</dt><dd>{selected.confidence===null?'Not supplied':`${(selected.confidence*100).toFixed(1)}%`}</dd></div><div><dt>Status</dt><dd className={selected.status}>{selected.status==='accepted'?'○ Accepted':'× Rejected'}</dd></div></dl>:<p>Choose a green circle or red cross to inspect its correspondence.</p>}</>:<p>{completed?'The backend did not return point coordinates.':'Run Registration to inspect corresponding points.'}</p>}</div>}
        <details className="pipeline-card" open={w.pipelineOpen} onToggle={e=>w.setPipelineOpen(e.currentTarget.open)}><summary><div><span className="eyebrow">REGISTRATION PIPELINE</span><small>{stage==='running'?(uploaded?'Processing on backend…':PIPELINE[w.activeIndex]):completed?(uploaded?'Backend processing complete':'7 stages complete'):'Ready to process image pair'}</small></div><strong>{w.progress}%</strong><ChevronDown/></summary><Progress value={w.progress}><ProgressLabel className="sr-only">Registration pipeline</ProgressLabel><ProgressValue className="sr-only"/></Progress><div className="pipeline-stages">{PIPELINE.map((name,i)=><div key={name} className={i<w.activeIndex?'done':i===w.activeIndex&&stage==='running'?'running':''}><span>{uploaded&&i===0&&!source.label&&!reference.label?'—':i<w.activeIndex?'✓':i===w.activeIndex&&stage==='running'?'◌':String(i+1).padStart(2,'0')}</span>{uploaded&&i===5?(w.result?.metrics.registration_method||'Backend Alignment'):name}{uploaded&&i===0&&!source.label&&!reference.label&&<small>Not supplied</small>}</div>)}</div></details>
        <details className="processing-log" open={w.logOpen} onToggle={e=>w.setLogOpen(e.currentTarget.open)}><summary><span className="eyebrow">PROCESSING LOG</span><span>{w.logs.length} entries</span><ChevronDown/></summary><div className="log-lines" role="log" aria-live="polite">{w.logs.map((line,i)=><div key={`${i}-${line}`}>{line}</div>)}</div></details>
      </section>
      <aside className="metrics-panel"><Tabs defaultValue="quality"><TabsList className="w-full"><TabsTrigger value="quality">Quality</TabsTrigger><TabsTrigger value="telemetry">Telemetry</TabsTrigger></TabsList><TabsContent value="quality"><div className={`simulation-notice ${!simulated?'backend':''}`}>{simulated?'SIMULATED PROTOTYPE RESULTS':'BACKEND RESULTS'}</div><div className="score-card"><div className="score-ring"><strong>{completed?metrics.rmse_px.toFixed(2):'—'}</strong><span>px RMSE</span></div><div><span>ACCURACY GATE</span><b>{completed?(metrics.rmse_px<.5?'PASS':'REVIEW'):'AWAITING RUN'}</b><small>{simulated?'Illustrative threshold':'Model-inlier residual'}<br/>&lt; 0.50 px</small></div></div>
        <div className="metric-list"><Metric icon={<CircleDot/>} label="Accepted Matches" value={completed?String(metrics.accepted_matches):'—'} detail={completed?`of ${metrics.candidate_matches} candidates`:''}/><Metric icon={<X/>} label="Rejected Matches" value={completed?String(metrics.candidate_matches-metrics.accepted_matches):'—'}/><Metric icon={<ShieldCheck/>} label="Inlier Ratio" value={completed?`${(metrics.inlier_ratio*100).toFixed(1)}%`:'—'}/><Metric icon={<Gauge/>} label="Spatial Coverage" value={completed?`${(metrics.spatial_coverage*100).toFixed(0)}%`:'—'}/><Metric icon={<Activity/>} label="Runtime" value={completed?`${metrics.runtime_seconds.toFixed(2)} s`:'—'} detail={simulated?'Illustrative processing time':'Measured by backend'}/></div>
        <div className="method-row"><span>REGISTRATION METHOD</span><b>{completed?metrics.engine:'Awaiting run'}</b><small>{completed?(metrics.registration_method||'Backend reported method'):''}</small></div>
        <div className="coverage"><div className="section-caption">SPATIAL MATCH COVERAGE</div><div className="coverage-map">{w.referencePreview&&<img src={w.referencePreview} alt="Reference lunar image" onLoad={e=>setCoverageSize({width:e.currentTarget.naturalWidth,height:e.currentTarget.naturalHeight})}/>}<svg viewBox={`0 0 ${coverageSize.width} ${coverageSize.height}`} preserveAspectRatio="xMidYMid meet" aria-label="Accepted match distribution">{points.filter(p=>p.status==='accepted').map(p=><circle key={p.id} cx={p.reference_x} cy={p.reference_y} r={coverageSize.width*.009} fill="#61e6a1" stroke="#071018" strokeWidth={coverageSize.width*.002}/>)}</svg>{!points.length&&<span>No point coordinates available</span>}</div><p><span className="accepted">●</span> Accepted matches across the reference extent</p></div>
        <div className="audit-note"><ShieldCheck/><div><b>{simulated?'Demonstration only':'Inspect before scientific use'}</b><p>{simulated?'RMSE, matches, coverage and runtime are simulated. No experimental accuracy is claimed.':'Backend RMSE uses model inliers. Independent checkpoints are required for validation.'}</p></div></div>
        <DropdownMenu><DropdownMenuTrigger render={<Button variant="outline" className="export" disabled={!completed}/>}><Download/> Export<ChevronDown/></DropdownMenuTrigger><DropdownMenuContent className="export-menu"><DropdownMenuItem onClick={w.exportGeoTiff}>Export Registered GeoTIFF</DropdownMenuItem><DropdownMenuItem disabled={!points.length} onClick={w.exportCSV}>Export Tie Points CSV</DropdownMenuItem><DropdownMenuItem onClick={w.exportReport}>Export Registration Report</DropdownMenuItem></DropdownMenuContent></DropdownMenu>
      </TabsContent><TabsContent value="telemetry"><div className="simulation-notice">{uploaded?'LOADED DATASET METADATA':'EXAMPLE ACQUISITION METADATA'}</div><div className="telemetry-list">{[['Source sensor',source.metadata.sensor],['Source GSD',source.metadata.gsd],['Source sun azimuth',source.metadata.sun],['Source incidence / emission',`${source.metadata.incidence} / ${source.metadata.emission}`],['Reference sensor',reference.metadata.sensor],['Reference GSD',reference.metadata.gsd],['Reference sun azimuth',reference.metadata.sun],['Reference incidence / emission',`${reference.metadata.incidence} / ${reference.metadata.emission}`],['Coordinates','Raster pixels · top-left origin'],['Georeferencing','Requires backend GeoTIFF']].map(([label,value])=><div key={label}><span>{label}</span><b>{value}</b></div>)}</div></TabsContent></Tabs></aside>
    </section><footer><Satellite/> Chandra-Align prototype <span/> Load → Register → Inspect → Validate → Export <ArrowRight/></footer>
    <Dialog open={w.settingsOpen} onOpenChange={w.setSettingsOpen}><DialogContent><DialogTitle>Processing service</DialogTitle><DialogDescription>Connect the LunarGrid backend for uploaded image pairs. The sample pair remains a local simulation.</DialogDescription><label className="settings-label" htmlFor="api-url">Service URL</label><input id="api-url" className="settings-input" type="url" value={w.draftEndpoint} onChange={e=>w.setDraftEndpoint(e.target.value)} placeholder="https://your-processing-service"/><p className="settings-help">The service must allow this site's origin and expose /register. TIFF and IMG files require a backend preview.</p><Button onClick={w.saveSettings}>Save connection</Button></DialogContent></Dialog>
    <Dialog open={w.exportNotice} onOpenChange={w.setExportNotice}><DialogContent><DialogTitle>Registered GeoTIFF</DialogTitle><DialogDescription>A georeferenced raster has not been returned by the backend. This preview has no verified lunar coordinate system.</DialogDescription><p>Connect a backend that supplies a registered GeoTIFF to enable this export. Tie Points CSV and the Registration Report are available now{simulated?' and explicitly marked as simulated':''}.</p><Button onClick={()=>w.setExportNotice(false)}>Understood</Button></DialogContent></Dialog>
  </main>;
}
function Metric({icon,label,value,detail}:{icon:React.ReactNode;label:string;value:string;detail?:string}){return <div className="metric"><div className="metric-icon">{icon}</div><div><span>{label}</span>{detail&&<small>{detail}</small>}</div><strong>{value}</strong></div>;}
